# self explanatory, just change window settings here
[window]
title = "Fly-in"
min_width = 50  # pixels - min is 500

# self explanatory :)
[appearance]
background_color = 0x202020ff
cenimatic_bars = false

# drone settings, also self explanatory
[drone]
enable_trail = true
position_randomness = 5  # pixels

[hub]
enable_name = true
enable_drone_count = true

[sizing]
spacing = 100  # pixels - min is 32 pixel
padding = [200, 0]  # pixels - min is [0, 80]

# dev options
[other]
enable_help_tip = true
help_tip_text = "SPACE to pause/resume  |  LEFT/RIGHT to change speed  |  ESC or Q to quit"
