# Warning: this is a config file, meant for advanced users only.
# Changing values here may break the program or cause unexpected behavior.
# If you don't know what you're doing, don't change anything.

[window]
title = "Fly-in"
min_width = 500 # atleast 500

[appearance]
theme = "light"
background_color = 0x202020ff
cenimatic_bars = false

[drone]
enable_trail = true
position_randomness = 10

[hub]
enable_name = true
enable_drone_count = true

[sizing]
spacing = 0
padding_x = 25 # atleast 25
padding_y = 50 # atleast 50

[other]
enable_help_tip = true
help_tip_text = "SPACE to pause/resume  |  LEFT/RIGHT to change speed  |  ESC or Q to quit"
