# Warning: this is a config file, meant for devs only.
# Changing values here may break the program or cause unexpected behavior.
# If you don't know what you're doing, go away.

[window]
title = "Fly-in"
min_width = 500

[appearance]
theme = "light"
background_color = 0x202020ff
cenimatic_bars = false

[drone]
enable_trail = true
trail_opacity = 0.8
position_randomness = 10

[hub]
enable_name = true
name_color = 0xFFFFFFFF
enable_hub_stats = true

[connection]
color = 0xFFFFFF20
text_color = 0xFFFFFFFF
stroke_color = 0x000000FF

[sizing]
spacing = 48
padding_x = 100
padding_y = 75

[other]
enable_help_tip = true
help_tip_text = "SPACE  pause/resume  |  < / >  speed  |  ESC/Q  quit  | T  drone trails"
